runtime: python38

default_expiration: "2h"
entrypoint: main.app

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /manifest.json
  static_files: img/manifest.json
  upload: img/manifest.json

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /data
  static_dir: data

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /progress/.*
  script: auto
  secure: always

- url: /tasks/.*
  script: auto
  secure: always
  
- url: /admin/.*
  script: auto
  secure: always
  
- url: .*  # This regex directs all routes to main.app
  script: auto
  secure: always
