runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "2h"

libraries:
- name: ssl
  version: latest
- name: lxml
  version: latest

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /manifest.json
  static_files: img/manifest.json
  upload: img/manifest.json

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /testdata
  static_dir: tests/data
  application_readable: true

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: "/terminsprogram/.*"
  script: main.app
  login: optional
  secure: optional

- url: /progress/.*
  script: main.app
  login: required
  secure: always

- url: /tasks/.*
  script: main.app
  login: admin
  secure: always
  
- url: /admin/.*
  script: main.app
  login: admin
  secure: always

- url: /login/.*
  script: main.app
  login: optional
  secure: always

- url: /sessionLogin/.*
  script: main.app
  login: optional
  secure: always

- url: /loggedIn/.*
  script: main.app
  login: optional
  secure: always

- url: .*  # This regex directs all routes to main.app
  script: main.app
  login: optional
  secure: always



env_variables:
  GAE_USE_SUBPROCESS: 0
