runtime: python27
api_version: 1
threadsafe: yes
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.ini$
- ^(.*/)?\.vscode$
- ^(.*/)?\.pdf$

default_expiration: "2h"

libraries:
- name: ssl
  version: latest
- name: lxml
  version: latest
  
builtins:
- deferred: on
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /manifest.json
  static_files: img/manifest.json
  upload: img/manifest.json

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /data
  static_dir: data
  application_readable: true

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /progress/.*
  script: main.app
  login: required
  secure: always

- url: /tasks/.*
  script: main.app
  login: admin
  secure: always
  
- url: /admin/.*
  script: main.app
  login: admin
  secure: always
  
- url: .*  # This regex directs all routes to main.app
  script: main.app
  login: required
  secure: always
