trigger:
  - azure/test # TODO change to master later
pr:
  - azure/test # TODO change to master later

jobs:
  - template: templates/build-service.job.yaml
    parameters:
      serviceName: skojjt
      subPath: ./
      stepsTemplate: build.yaml
  - template: templates/deploy-service.job.yaml
    parameters:
      serviceName: skojjt
      stepsTemplate: build.yaml
