trigger:
  - azure/test # TODO change to master later
pr:
  - azure/test # TODO change to master later

variables:
  serviceName: skojjt

stages:
  - stage: ${{ format('build_pipleine_{0}', variables.serviceName) }}
    jobs:
      - template: templates/build-service.job.yaml
        parameters:
          serviceName: parameters.serviceName
          subPath: ./
          stepsTemplate: build.yaml
  - stage: Deploy to Beta
    jobs:
      - deployment: ${{ format('beta_deploy_{0}', variables.serviceName) }}
        displayName: ${{ format('Beta Deploy {0}', variables.serviceName) }}
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Fake beta script
  - stage: Github Tag version
    jobs:
      - deployment: ${{ format('tag_{0}', variables.serviceName) }}
        displayName: ${{ format('Tag {0} version', variables.serviceName) }}
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Fake tag script
  - stage: Deploy to Production
    jobs:
      - deployment: ${{ format('deploy_{0}', variables.serviceName) }}
        displayName: ${{ format('Deploy {0}', variables.serviceName) }}
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Fake live-server script
