parameters:
  serviceName: ''
  stepsTemplate: ''

stages:
- stage: Deploy to Beta
  jobs:
    - deployment: ${{ format('beta_deploy_{0}', parameters.serviceName) }}
      displayName: ${{ format('Beta Deploy {0}', parameters.serviceName) }}
      steps:
        script: echo Fake beta script
- stage: Github Tag version
  jobs:
    - deployment: ${{ format('tag_{0}', parameters.serviceName) }}
      displayName: ${{ format('Tag {0} version', parameters.serviceName) }}
      steps:
        script: echo Fake tag script
- stage: Deploy to Production
  jobs:
    - deployment: ${{ format('tag_{0}', parameters.serviceName) }}
      displayName: ${{ format('Tag {0} version', parameters.serviceName) }}
      steps:
        script: echo Fake live-server script
